### ISSUE TITLE
Red Text Error

### ISSUE THREAD

**Issue by panzer168** [NecronomiconCoding/Pokemon-Go-Bot#11]
[10:25:15] Exception: PokemonGo.RocketAPI.Exceptions.InvalidResponseException: E
xception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException' was t
hrown.
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0
`2.MoveNext() in C:\Users\Leo\Desktop\Second\PokemonGo.RocketAPI\Extensions\Http
ClientExtensions.cs:line 22
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Client.<GetInventory>d__41.MoveNext() in C:\Users\Leo\
Desktop\Second\PokemonGo.RocketAPI\Client.cs:line 337
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Inventory.<GetPlayerStats>d__8.MoveNext() in C:\
Users\Leo\Desktop\Second\PokemonGo.RocketAPI.Logic\Inventory.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<DisplayPlayerLevelInTitle>d__17.MoveNext(
) in C:\Users\Leo\Desktop\Second\PokemonGo.RocketAPI.Logic\Logic.cs:line 266
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__6.MoveNext() in C:\Us
ers\Leo\Desktop\Second\PokemonGo.RocketAPI.Logic\Logic.cs:line 62

**Comment by kevvv** [comment]
What did you do to fix it?  I just moved DisplayPlayerLevelInTitle out of the loop (haven't fully tested)
