### ISSUE TITLE
crash  with ptc, work with google. 

### ISSUE THREAD

**Issue by gotrock20** [NecronomiconCoding/Pokemon-Go-Bot#39]
i ran google and it work fine, but ptc crash on me. 

[12:25:48] (INFO) Awesome! You have already got the newest version! 1.0.1.2
[12:25:48] (WARNING) Make sure Lat & Lng is right. Exit Program if not! Lat: 40.764731 Lng: -73.973073
[12:25:51] (INFO) Logging in via: Ptc
[12:26:11] (ERROR) ArgumentNullException - Restarting
[12:26:11] (INFO) Awesome! You have already got the newest version! 1.0.1.2
[12:26:11] (WARNING) Make sure Lat & Lng is right. Exit Program if not! Lat: 40.764731 Lng: -73.973073
[12:26:14] (INFO) Logging in via: Ptc
[12:26:53] (INFO) Access token expired
[12:27:25] (ERROR) Unhandled exception: System.AggregateException: One or more errors occurred. ---> PokemonGo.RocketAPI.Exceptions.PtcOfflineException: Exception of type 'PokemonGo.RocketAPI.Exceptions.PtcOfflineException' was thrown.
   at PokemonGo.RocketAPI.Login.PtcLogin.<GetAccessToken>d__0.MoveNext() in C:\Users\a\Desktop\h\PokemonGo.RocketAPI\Login\PtcLogin.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Client.<DoPtcLogin>d__26.MoveNext() in C:\Users\a\Desktop\h\PokemonGo.RocketAPI\Client.cs:line 121
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__10.MoveNext() in C:\Users\a\Desktop\h\PokemonGo.RocketAPI.Logic\Logic.cs:line 203
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__10.MoveNext() in C:\Users\a\Desktop\h\PokemonGo.RocketAPI.Logic\Logic.cs:line 233
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at PokemonGo.RocketAPI.Console.Program.<>c.<Main>b__0_0() in C:\Users\a\Desktop\h\PokemonGo.RocketAPI.Console\Program.cs:line 21
---> (Inner Exception #0) PokemonGo.RocketAPI.Exceptions.PtcOfflineException: Exception of type 'PokemonGo.RocketAPI.Exceptions.PtcOfflineException' was thrown.
   at PokemonGo.RocketAPI.Login.PtcLogin.<GetAccessToken>d__0.MoveNext() in C:\Users\a\Desktop\h\PokemonGo.RocketAPI\Login\PtcLogin.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Client.<DoPtcLogin>d__26.MoveNext() in C:\Users\a\Desktop\h\PokemonGo.RocketAPI\Client.cs:line 121
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__10.MoveNext() in C:\Users\a\Desktop\h\PokemonGo.RocketAPI.Logic\Logic.cs:line 203
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__10.MoveNext() in C:\Users\a\Desktop\h\PokemonGo.RocketAPI.Logic\Logic.cs:line 233<---

**Comment by cryy** [comment]
Ptc is down

**Comment by gotrock20** [comment]
o thank :
