### ISSUE TITLE
[BUG] Crashes

### ISSUE THREAD

**Issue by deknarf** [NecronomiconCoding/Pokemon-Go-Bot#42]
Bot-master (2)\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__13.MoveNext() in C:\Users\Frank\Downloads\Pokemon-Go-Bot-master (2)\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.cs:line 273
[21:47:13] (ERROR) Exception: PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException' was thrown.
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in C:\Users\Frank\Downloads\Pokemon-Go-Bot-master (2)\Pokemon-Go-Bot-master\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Client.<GetInventory>d__30.MoveNext() in C:\Users\Frank\Downloads\Pokemon-Go-Bot-master (2)\Pokemon-Go-Bot-master\PokemonGo.RocketAPI\Client.cs:line 183
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Inventory.<GetPlayerStats>d__7.MoveNext() in C:\Users\Frank\Downloads\Pokemon-Go-Bot-master (2)\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Inventory.cs:line 116
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<DisplayPlayerLevelInTitle>d__7.MoveNext() in C:\Users\Frank\Downloads\Pokemon-Go-Bot-master (2)\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__13.MoveNext() in C:\Users\Frank\Downloads\Pokemon-Go-Bot-master (2)\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.cs:line 273

**Comment by NecronomiconCoding** [comment]
known issue

**Comment by deknarf** [comment]
k sorry :+1:
