### ISSUE TITLE
Ptc Login Issue?

### ISSUE THREAD

**Issue by Krovasan** [NecronomiconCoding/Pokemon-Go-Bot#49]
[14:09:43] (INFO) Awesome! You have already got the newest version! 1.0.1.5
[14:09:43] (WARNING) Make sure Lat & Lng is right. Exit Program if not! Lat: 40.
770648 Lng: -73.974755
[14:09:46] (INFO) Logging in via: Ptc
[14:10:01] (ERROR) ArgumentNullException - Restarting
[14:10:01] (INFO) Awesome! You have already got the newest version! 1.0.1.5
[14:10:01] (WARNING) Make sure Lat & Lng is right. Exit Program if not! Lat: 40.
770648 Lng: -73.974755
[14:10:04] (INFO) Logging in via: Ptc
[14:10:24] (INFO) Access token expired
[14:10:36] (ERROR) Unhandled exception: System.AggregateException: One or more e
rrors occurred. ---> PokemonGo.RocketAPI.Exceptions.PtcOfflineException: Excepti
on of type 'PokemonGo.RocketAPI.Exceptions.PtcOfflineException' was thrown.
   at PokemonGo.RocketAPI.Login.PtcLogin.<GetAccessToken>d__0.MoveNext() in H:\D
ownloads\Pokemongo\trunk\PokemonGo.RocketAPI\Login\PtcLogin.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Client.<DoPtcLogin>d__26.MoveNext() in H:\Downloads\Po
kemongo\trunk\PokemonGo.RocketAPI\Client.cs:line 129
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__11.MoveNext() in H:\Downloads\
Pokemongo\trunk\PokemonGo.RocketAPI.Logic\Logic.cs:line 207
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__11.MoveNext() in H:\Downloads\
Pokemongo\trunk\PokemonGo.RocketAPI.Logic\Logic.cs:line 237
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceled
Exceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationTo
ken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at PokemonGo.RocketAPI.Console.Program.<>c.<Main>b__0_0() in H:\Downloads\Pok
emongo\trunk\PokemonGo.RocketAPI.Console\Program.cs:line 22
---> (Inner Exception #0) PokemonGo.RocketAPI.Exceptions.PtcOfflineException: Ex
ception of type 'PokemonGo.RocketAPI.Exceptions.PtcOfflineException' was thrown.

   at PokemonGo.RocketAPI.Login.PtcLogin.<GetAccessToken>d__0.MoveNext() in H:\D
ownloads\Pokemongo\trunk\PokemonGo.RocketAPI\Login\PtcLogin.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Client.<DoPtcLogin>d__26.MoveNext() in H:\Downloads\Po
kemongo\trunk\PokemonGo.RocketAPI\Client.cs:line 129
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__11.MoveNext() in H:\Downloads\
Pokemongo\trunk\PokemonGo.RocketAPI.Logic\Logic.cs:line 207
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__11.MoveNext() in H:\Downloads\
Pokemongo\trunk\PokemonGo.RocketAPI.Logic\Logic.cs:line 237<---

**Comment by BioMuell** [comment]
PTC server are unstable, not BOT's fault
