### ISSUE TITLE
Crashes after however long of use

### ISSUE THREAD

**Issue by Opzon** [NecronomiconCoding/Pokemon-Go-Bot#71]
(use is probably no longer than 30 or so minutes)
```
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__13.MoveNext() in C:\U
sers\Riot\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.cs:line
273
[14:24:59] (ERROR) Exception: PokemonGo.RocketAPI.Exceptions.InvalidResponseExce
ption: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseExceptio
n' was thrown.
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1
`2.MoveNext() in C:\Users\Riot\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI
\Extensions\HttpClientExtensions.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Client.<GetInventory>d__30.MoveNext() in C:\Users\Riot
\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI\Client.cs:line 183
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Inventory.<GetPlayerStats>d__7.MoveNext() in C:\
Users\Riot\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Inventory.cs:
line 116
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<DisplayPlayerLevelInTitle>d__7.MoveNext()
 in C:\Users\Riot\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.
cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__13.MoveNext() in C:\U
sers\Riot\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.cs:line
273
[14:25:09] (ERROR) Exception: PokemonGo.RocketAPI.Exceptions.InvalidResponseExce
ption: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseExceptio
n' was thrown.
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1
`2.MoveNext() in C:\Users\Riot\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI
\Extensions\HttpClientExtensions.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Client.<GetInventory>d__30.MoveNext() in C:\Users\Riot
\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI\Client.cs:line 183
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Inventory.<GetPlayerStats>d__7.MoveNext() in C:\
Users\Riot\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Inventory.cs:
line 116
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<DisplayPlayerLevelInTitle>d__7.MoveNext()
 in C:\Users\Riot\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.
cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__13.MoveNext() in C:\U
sers\Riot\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.cs:line
273
[14:25:19] (ERROR) Exception: PokemonGo.RocketAPI.Exceptions.InvalidResponseExce
ption: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseExceptio
n' was thrown.
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1
`2.MoveNext() in C:\Users\Riot\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI
\Extensions\HttpClientExtensions.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Client.<GetInventory>d__30.MoveNext() in C:\Users\Riot
\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI\Client.cs:line 183
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Inventory.<GetPlayerStats>d__7.MoveNext() in C:\
Users\Riot\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Inventory.cs:
line 116
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<DisplayPlayerLevelInTitle>d__7.MoveNext()
 in C:\Users\Riot\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.
cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__13.MoveNext() in C:\U
sers\Riot\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.cs:line
273
[14:25:30] (ERROR) Exception: PokemonGo.RocketAPI.Exceptions.InvalidResponseExce
ption: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseExceptio
n' was thrown.
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1
`2.MoveNext() in C:\Users\Riot\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI
\Extensions\HttpClientExtensions.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Client.<GetInventory>d__30.MoveNext() in C:\Users\Riot
\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI\Client.cs:line 183
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Inventory.<GetPlayerStats>d__7.MoveNext() in C:\
Users\Riot\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Inventory.cs:
line 116
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<DisplayPlayerLevelInTitle>d__7.MoveNext()
 in C:\Users\Riot\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.
cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__13.MoveNext() in C:\U
sers\Riot\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.cs:line
273
[14:25:40] (ERROR) Exception: PokemonGo.RocketAPI.Exceptions.InvalidResponseExce
ption: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseExceptio
n' was thrown.
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1
`2.MoveNext() in C:\Users\Riot\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI
\Extensions\HttpClientExtensions.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Client.<GetInventory>d__30.MoveNext() in C:\Users\Riot
\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI\Client.cs:line 183
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Inventory.<GetPlayerStats>d__7.MoveNext() in C:\
Users\Riot\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Inventory.cs:
line 116
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<DisplayPlayerLevelInTitle>d__7.MoveNext()
 in C:\Users\Riot\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.
cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__13.MoveNext() in C:\U
sers\Riot\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.cs:line
273
[14:25:50] (ERROR) Exception: PokemonGo.RocketAPI.Exceptions.InvalidResponseExce
ption: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseExceptio
n' was thrown.
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1
`2.MoveNext() in C:\Users\Riot\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI
\Extensions\HttpClientExtensions.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Client.<GetInventory>d__30.MoveNext() in C:\Users\Riot
\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI\Client.cs:line 183
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Inventory.<GetPlayerStats>d__7.MoveNext() in C:\
Users\Riot\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Inventory.cs:
line 116
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<DisplayPlayerLevelInTitle>d__7.MoveNext()
 in C:\Users\Riot\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.
cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__13.MoveNext() in C:\U
sers\Riot\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.cs:line
273
[14:26:00] (ERROR) Exception: PokemonGo.RocketAPI.Exceptions.InvalidResponseExce
ption: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseExceptio
n' was thrown.
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1
`2.MoveNext() in C:\Users\Riot\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI
\Extensions\HttpClientExtensions.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Client.<GetInventory>d__30.MoveNext() in C:\Users\Riot
\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI\Client.cs:line 183
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Inventory.<GetPlayerStats>d__7.MoveNext() in C:\
Users\Riot\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Inventory.cs:
line 116
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<DisplayPlayerLevelInTitle>d__7.MoveNext()
 in C:\Users\Riot\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.
cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__13.MoveNext() in C:\U
sers\Riot\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.cs:line
273
[14:26:10] (ERROR) Exception: PokemonGo.RocketAPI.Exceptions.InvalidResponseExce
ption: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseExceptio
n' was thrown.
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1
`2.MoveNext() in C:\Users\Riot\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI
\Extensions\HttpClientExtensions.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Client.<GetInventory>d__30.MoveNext() in C:\Users\Riot
\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI\Client.cs:line 183
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Inventory.<GetPlayerStats>d__7.MoveNext() in C:\
Users\Riot\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Inventory.cs:
line 116
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<DisplayPlayerLevelInTitle>d__7.MoveNext()
 in C:\Users\Riot\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.
cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__13.MoveNext() in C:\U
sers\Riot\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.cs:line
273

```

**Comment by nrmodesto** [comment]
I think it's fixed by the recent version. Please download and configure it again.

**Comment by Hitsuomy** [comment]
Known bug, latest version should fix it, build again and see if it works.

**Comment by Opzon** [comment]
There have been so many updates today lol. Loving it :D just downloaded new version and have it running right now. Will post again if there are issues still. thanks for the insanely fast response guys!

**Comment by Opzon** [comment]
Hmm.. now it crashes at login

`[14:36:49] (INFO) Logging in via: Ptc
[14:37:02] (ERROR) Unhandled exception: System.AggregateException: One or more e
rrors occurred. ---> Newtonsoft.Json.JsonReaderException: Unexpected character e
ncountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings sett
ings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)

   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at PokemonGo.RocketAPI.Helpers.JsonHelper.GetValue(String json, String key) i
n C:\Users\Riot\Desktop\Pzokemon-Go-Bot-master\PokemonGo.RocketAPI\Helpers\JsonH
elper.cs:line 13
   at PokemonGo.RocketAPI.Login.PtcLogin.<GetAccessToken>d__0.MoveNext() in C:\U
sers\Riot\Desktop\Pzokemon-Go-Bot-master\PokemonGo.RocketAPI\Login\PtcLogin.cs:l
ine 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Client.<DoPtcLogin>d__26.MoveNext() in C:\Users\Riot\D
esktop\Pzokemon-Go-Bot-master\PokemonGo.RocketAPI\Client.cs:line 129
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__11.MoveNext() in C:\Users\Riot
\Desktop\Pzokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.cs:line 213
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceled
Exceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationTo
ken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at PokemonGo.RocketAPI.Console.Program.<>c.<Main>b__0_0() in C:\Users\Riot\De
sktop\Pzokemon-Go-Bot-master\PokemonGo.RocketAPI.Console\Program.cs:line 22
---> (Inner Exception #0) Newtonsoft.Json.JsonReaderException: Unexpected charac
ter encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings sett
ings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)

   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at PokemonGo.RocketAPI.Helpers.JsonHelper.GetValue(String json, String key) i
n C:\Users\Riot\Desktop\Pzokemon-Go-Bot-master\PokemonGo.RocketAPI\Helpers\JsonH
elper.cs:line 13
   at PokemonGo.RocketAPI.Login.PtcLogin.<GetAccessToken>d__0.MoveNext() in C:\U
sers\Riot\Desktop\Pzokemon-Go-Bot-master\PokemonGo.RocketAPI\Login\PtcLogin.cs:l
ine 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Client.<DoPtcLogin>d__26.MoveNext() in C:\Users\Riot\D
esktop\Pzokemon-Go-Bot-master\PokemonGo.RocketAPI\Client.cs:line 129
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__11.MoveNext() in C:\Users\Riot
\Desktop\Pzokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.cs:line 213<---
`

**Comment by nrmodesto** [comment]
It's still not fixed in the last update...

**Comment by Hitsuomy** [comment]
Don't use ptc for login, ptc login server is HIGHLY unstable.

**Comment by nrmodesto** [comment]
It happens with google too...

**Comment by joshk6656** [comment]
I'm pretty sure these are only happening when the servers are having issues (which it has been for the last 45 minutes)

**Comment by nrmodesto** [comment]
Could be, but it's very weird.. it happens only after half an hour to all people..

**Comment by Mavmins** [comment]
its not login server related, and the data servers once you are logged in are the same, so i dont think its servers, plus its both ptc and google

**Comment by nrmodesto** [comment]
I thinks it's not the servers too... Because it's happens at a specific time after the first start of the app..

**Comment by ruxiao16** [comment]
Yea i dont think it is the server either

**Comment by ridoknight** [comment]
maybe they can save ur last cordinate then relog after 20 min.

**Comment by Opzon** [comment]
would be nice @ridoknight also, that #85 idea is nice too. hopefully these bots become more stable/better soon. nice to see tons of updates in such a small time frame :D

**Comment by joshk6656** [comment]
its interesting because it has a try/catch to restart on this exception... Someone should try modifying their program.cs to this to see if it catches the error and restarts. This is not a fix, it is a workaround if it works. I am at work and unable to test.

https://gist.github.com/joshk6656/46460795e582bae2357e13e2f4c10c8c

**Comment by NecronomiconCoding** [comment]
should have been fixed aroun 20min ago
