### ISSUE TITLE
'PokemonGo.RocketAPI.Exceptions.InvalidResponseExceptio n' was thrown.

### ISSUE THREAD

**Issue by MonsterMMORPG** [NecronomiconCoding/Pokemon-Go-Bot#72]
here the full error and it doesnt continue

```
[00:28:33] (ERROR) Exception: PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseExceptio
n' was thrown.
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI\Extensions\
HttpClientExtensions.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Client.<GetInventory>d__33.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI\Client.cs:line 207
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Inventory.<GetItems>d__7.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Inventory.cs:line 106
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Inventory.<GetItemAmountByType>d__6.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Inventory.cs:line 10
0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<GetBestBall>d__15.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 474
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<CatchEncounter>d__7.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 62
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<ExecuteCatchAllNearbyPokemons>d__13.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line
 320
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<ExecuteFarmingPokestopsAndPokemons>d__14.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs
:line 458
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__16.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 519
[00:28:43] (ERROR) Exception: PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseExceptio
n' was thrown.
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI\Extensions\
HttpClientExtensions.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Client.<GetInventory>d__33.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI\Client.cs:line 207
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Inventory.<GetPlayerStats>d__9.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Inventory.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<DisplayPlayerLevelInTitle>d__9.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 113
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__16.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 513
[00:28:54] (ERROR) Exception: PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseExceptio
n' was thrown.
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI\Extensions\
HttpClientExtensions.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Client.<GetInventory>d__33.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI\Client.cs:line 207
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Inventory.<GetPlayerStats>d__9.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Inventory.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<DisplayPlayerLevelInTitle>d__9.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 113
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__16.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 513
[00:29:04] (ERROR) Exception: PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseExceptio
n' was thrown.
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI\Extensions\
HttpClientExtensions.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Client.<GetInventory>d__33.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI\Client.cs:line 207
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Inventory.<GetPlayerStats>d__9.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Inventory.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<DisplayPlayerLevelInTitle>d__9.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 113
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__16.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 513
[00:29:15] (ERROR) Exception: PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseExceptio
n' was thrown.
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI\Extensions\
HttpClientExtensions.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Client.<GetInventory>d__33.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI\Client.cs:line 207
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Inventory.<GetPlayerStats>d__9.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Inventory.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<DisplayPlayerLevelInTitle>d__9.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 113
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__16.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 513
[00:29:25] (ERROR) Exception: PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseExceptio
n' was thrown.
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI\Extensions\
HttpClientExtensions.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Client.<GetInventory>d__33.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI\Client.cs:line 207
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Inventory.<GetPlayerStats>d__9.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Inventory.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<DisplayPlayerLevelInTitle>d__9.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 113
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__16.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 513
[00:29:50] (ERROR) Exception: PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseExceptio
n' was thrown.
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI\Extensions\
HttpClientExtensions.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Client.<GetInventory>d__33.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI\Client.cs:line 207
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Inventory.<GetPlayerStats>d__9.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Inventory.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<DisplayPlayerLevelInTitle>d__9.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 113
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__16.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 513
[00:30:01] (ERROR) Exception: PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseExceptio
n' was thrown.
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI\Extensions\
HttpClientExtensions.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Client.<GetInventory>d__33.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI\Client.cs:line 207
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Inventory.<GetPlayerStats>d__9.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Inventory.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<DisplayPlayerLevelInTitle>d__9.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 113
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__16.MoveNext() in D:\74 pokemon go\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 513
```

**Comment by stellaris1** [comment]
this is not fixed

**Comment by nrmodesto** [comment]
I confirm it's happening to me too. It seems to happen after ~30 minutes of first launch.

**Comment by Sylencer90** [comment]
last issue got deleted, idk why. Facing same issue every 30 mins.

**Comment by nrmodesto** [comment]
Yes, me too. And I have my token set up.. It happens to both PTC and Google...

**Comment by Mavmins** [comment]
yeah same as my issue that was closed, but i dont think its fixed yet

**Comment by nrmodesto** [comment]
They deleted the other topics regarding this issue..

**Comment by NecronomiconCoding** [comment]
That should have been fixed around 15 minutes ago. wait until it happens again and reopen

**Comment by ShawnHardwick** [comment]
@NecronomiconCoding I had another user run into this issue in 0.1.9.

See attached:
https://cdn.discordapp.com/attachments/206065340579315712/208061335001366549/Exception.JPG
